// Listado completo de países que usan IBAN en 2026
const bancosIBAN = [
  // Europa y SEPA
  { pais: "Albania", banco: "Raiffeisen Bank Albania" },
  { pais: "Andorra", banco: "Andbank" },
  { pais: "Austria", banco: "Erste Group" },
  { pais: "Bélgica", banco: "KBC Bank" },
  { pais: "Bosnia y Herzegovina", banco: "UniCredit Bank" },
  { pais: "Bulgaria", banco: "DSK Bank" },
  { pais: "Croacia", banco: "Zagrebačka banka" },
  { pais: "Chipre", banco: "Bank of Cyprus" },
  { pais: "República Checa", banco: "Česká spořitelna" },
  { pais: "Dinamarca", banco: "Danske Bank" },
  { pais: "Estonia", banco: "Swedbank" },
  { pais: "Finlandia", banco: "Nordea" },
  { pais: "Francia", banco: "BNP Paribas" },
  { pais: "Alemania", banco: "Deutsche Bank" },
  { pais: "Gibraltar", banco: "Gibraltar International Bank" },
  { pais: "Grecia", banco: "National Bank of Greece" },
  { pais: "Hungría", banco: "OTP Bank" },
  { pais: "Islandia", banco: "Landsbankinn" },
  { pais: "Irlanda", banco: "Bank of Ireland" },
  { pais: "Italia", banco: "Intesa Sanpaolo" },
  { pais: "Kosovo", banco: "ProCredit Bank Kosovo" },
  { pais: "Letonia", banco: "SEB Banka" },
  { pais: "Liechtenstein", banco: "LGT Bank" },
  { pais: "Lituania", banco: "Swedbank" },
  { pais: "Luxemburgo", banco: "Banque et Caisse d'Épargne" },
  { pais: "Malta", banco: "Bank of Valletta" },
  { pais: "Mónaco", banco: "CMB Monaco" },
  { pais: "Montenegro", banco: "Crnogorska Komercijalna Banka" },
  { pais: "Países Bajos", banco: "ING" },
  { pais: "Macedonia del Norte", banco: "Komercijalna Banka" },
  { pais: "Noruega", banco: "DNB ASA" },
  { pais: "Polonia", banco: "PKO Bank Polski" },
  { pais: "Portugal", banco: "Caixa Geral de Depósitos" },
  { pais: "Rumanía", banco: "Banca Transilvania" },
  { pais: "San Marino", banco: "Cassa di Risparmio di San Marino" },
  { pais: "Serbia", banco: "Banca Intesa Beograd" },
  { pais: "Eslovaquia", banco: "Slovenská sporiteľňa" },
  { pais: "Eslovenia", banco: "Nova Ljubljanska Banka" },
  { pais: "España", banco: "BBVA" },
  { pais: "Suecia", banco: "Swedbank" },
  { pais: "Suiza", banco: "UBS" },
  { pais: "Turquía", banco: "Türkiye İş Bankası" },
  { pais: "Reino Unido", banco: "HSBC" },
  { pais: "Vaticano", banco: "IOR (Banco del Vaticano)" },

  // Medio Oriente y Asia
  { pais: "Israel", banco: "Bank Leumi" },
  { pais: "Arabia Saudí", banco: "National Commercial Bank" },
  { pais: "Emiratos Árabes Unidos", banco: "Emirates NBD" },
  { pais: "Qatar", banco: "Qatar National Bank" },
  { pais: "Kuwait", banco: "National Bank of Kuwait" },
  { pais: "Bahréin", banco: "Bank of Bahrain and Kuwait" },
  { pais: "Jordania", banco: "Arab Bank" },
  { pais: "Líbano", banco: "Bank Audi" },
  { pais: "Pakistán", banco: "Habib Bank" },
  { pais: "Georgia", banco: "TBC Bank" },
  { pais: "Kazajistán", banco: "Halyk Bank" },

  // África
  { pais: "Egipto", banco: "National Bank of Egypt" },
  { pais: "Túnez", banco: "Banque de Tunisie" },
  { pais: "Argelia", banco: "Banque Extérieure d’Algérie" },
  { pais: "Mauritania", banco: "Banque Mauritanienne" },
  { pais: "Libia", banco: "Libyan Foreign Bank" },
  { pais: "Seychelles", banco: "Seychelles Commercial Bank" },
  { pais: "Sudán", banco: "Bank of Khartoum" },
  { pais: "Somalia", banco: "Premier Bank Somalia" },
  { pais: "Cabo Verde", banco: "Caixa Económica de Cabo Verde" },
  { pais: "Djibouti", banco: "Banque pour le Commerce et l’Industrie" },

  // América Latina y Caribe
  { pais: "Costa Rica", banco: "Banco Nacional de Costa Rica" },
  { pais: "República Dominicana", banco: "Banco Popular Dominicano" },
  { pais: "El Salvador", banco: "Banco Agrícola" },
  { pais: "Guatemala", banco: "Banco Industrial" },
  { pais: "Honduras", banco: "Banco Atlántida" },
  { pais: "Nicaragua", banco: "Banco de la Producción" },
  { pais: "Brasil", banco: "Banco do Brasil" }
];
